<a href="https://colab.research.google.com/github/MarkVoitov/DS_ABB/blob/main/%D0%A3%D0%BF%D1%80%D0%B0%D0%B6%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Упражнения с NumPy 

Давайте проверим ваши знания. Мы начнем с нескольких простых задач, а затем вам будут заданы несколько более сложных вопросов.

#### 1. Импорт NumPy 

In [1]:
import numpy as np

#### 2. Создать массив из 10 нулей

In [2]:
np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# DON'T WRITE HERE

#### 3. Создать массив из 10 единиц

In [5]:
np.array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [6]:
np.ones((10,), dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [7]:
# DON'T WRITE HERE

#### 4. Создать массив из  10 пятерок

In [8]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [9]:
np.ones((10,), dtype=int) * 5

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [10]:
# DON'T WRITE HERE

#### 5. Создать массив из целых чисел от 10 до 50

In [11]:
np.arange(10, 51)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [12]:
# DON'T WRITE HERE

#### 6. Создать массив из четных числел от 10 до 50

In [13]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [14]:
# DON'T WRITE HERE

#### 7. Создать матрицу 3х3 с числами от 0 до 8

In [15]:
np.array([[0,1,2],[3,4,5],[6,7,8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
# DON'T WRITE HERE

#### 8. Создать единичную матрицу 3x3 

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
# DON'T WRITE HERE

#### 9. Используйте NumPy для генерации случайного числа от 0 до 1
<br>ПРИМЕЧАНИЕ. Значение вашего результата должно отличаться от приведенного ниже.

In [19]:
np.random.rand(1)

array([0.73287615])

In [20]:
# DON'T WRITE HERE

#### Используйте NumPy для генерации массива из 25 случайных чисел, взятых из стандартного нормального распределения
<br>ПРИМЕЧАНИЕ. Значение вашего результата должно отличаться от приведенного ниже.

In [21]:
np.array([np.random.random() for i in range(25)])

array([0.21865642, 0.26737179, 0.3035213 , 0.59989593, 0.85046033,
       0.81707978, 0.17732435, 0.54691488, 0.73831842, 0.72316928,
       0.62235707, 0.80620273, 0.75913976, 0.02150361, 0.51415862,
       0.78681289, 0.5164247 , 0.39672145, 0.45390126, 0.24501553,
       0.69735599, 0.33352849, 0.6160802 , 0.20847668, 0.93306724])

In [22]:
np.random.rand(25)

array([0.49798798, 0.68441903, 0.82752063, 0.61614704, 0.56894138,
       0.70540378, 0.48587319, 0.82222851, 0.03461779, 0.71563154,
       0.8612537 , 0.15864555, 0.87662589, 0.4362942 , 0.00508438,
       0.10287384, 0.84852952, 0.44726983, 0.80443477, 0.31856492,
       0.49718644, 0.30442811, 0.40732851, 0.8559849 , 0.38439721])

In [23]:
# DON'T WRITE HERE

#### 11. Создайте следующую матрицу:

In [24]:
np.arange(1,101).reshape(10,10) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [25]:
# DON'T WRITE HERE

#### 12. Создайте массив из 20 линейно расположенных точек между 0 и 1:

In [26]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [27]:
# DON'T WRITE HERE

## Numpy индексация и выборка

Дана стартовая матрица (обязательно запустите ячейку ниже!). Вам необходимо повторить выходные результаты матрицы:

In [28]:
# это наша стартовая матрица
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 13. Напишите код, который воспроизводит вывод, показанный ниже.


In [29]:
mat[2:,1:]


array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [30]:
# DON'T WRITE HERE

#### 14. Напишите код, который воспроизводит вывод, показанный ниже.

In [31]:
mat[3, 4]

20

In [32]:
# DON'T WRITE HERE

#### 15. Напишите код, который воспроизводит вывод, показанный ниже.

In [33]:
mat[0:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [34]:
# DON'T WRITE HERE

#### 16. Напишите код, который воспроизводит вывод, показанный ниже.

In [35]:
mat[4]

array([21, 22, 23, 24, 25])

In [36]:
# DON'T WRITE HERE

#### 17. Напишите код, который воспроизводит вывод, показанный ниже.

In [37]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [38]:
# DON'T WRITE HERE

## Операции NumPy 

#### 18. Получить сумму всех значений в матрице mat

In [39]:
mat.sum()

325

In [40]:
# DON'T WRITE HERE

#### 19. Получить стандартное отклонение в матрице mat

In [41]:
mat.std()

7.211102550927978

In [42]:
# DON'T WRITE HERE

#### 20. Получить сумму значений в колонках в матрице mat

In [43]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [44]:
# DON'T WRITE HERE

## Бонусный вопрос

Есть ли способ гарантировать, что мы всегда получим одинаковые случайные числа?

In [45]:
np.random.seed(0)
np.random.rand(3)

array([0.5488135 , 0.71518937, 0.60276338])

# Great Job!