<a href="https://colab.research.google.com/github/MarkVoitov/DS_ABB/blob/main/%D0%A3%D0%BF%D1%80%D0%B0%D0%B6%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch

### 1. Выполнить стандартный импорт
 torch и NumPy

In [1]:
import numpy as np
import torch
torch.__version__

'1.8.1+cu101'

In [2]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.dtype

dtype('int64')

In [5]:
x = torch.from_numpy(arr)
x

tensor([1, 2, 3, 4, 5])

In [6]:
type(x)

torch.Tensor

In [7]:
x.dtype

torch.int64

In [8]:
x.device

device(type='cpu')

In [9]:
a = torch.tensor([1,2,3], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(a + b)

tensor([5., 7., 9.])


In [10]:
torch.add(a, b)

tensor([5., 7., 9.])

In [11]:
torch.mul(a, b)

tensor([ 4., 10., 18.])

In [12]:
a.numel()

3

### 2. Установите случайное начальное число для NumPy и PyTorch на «42»
Это позволяет нам обмениваться одинаковыми «случайными» результатами.

In [13]:
np.random.seed(42)
torch.manual_seed(42)

### 3. Создайте массив NumPy с именем «arr», который содержит 6 случайных целых чисел от 0 (включительно) до 5 (исключительно)

In [14]:
arr = np.random.randint(0,5,6)
print(arr)

[3 4 2 4 4 1]


In [ ]:
# DON'T WRITE HERE

[3 4 2 4 4 1]


### 4. Создайте тензор "х" из массива выше

In [15]:
x = torch.from_numpy(arr)
x = x.type(torch.int32)
x

tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)

In [ ]:
# DON'T WRITE HERE

tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)


### 5. Измените тип (dtype) для x с int32 на int64
Note: 'int64' is also called 'LongTensor'

In [16]:
x = x.type(torch.int64)
print(x.type())

torch.LongTensor


In [ ]:
# DON'T WRITE HERE

torch.LongTensor


### 6. Преобразуйте х в тензор 3х2
Есть несколько способов сделать это.

In [17]:
x = x.reshape(3,2)
x

tensor([[3, 4],
        [2, 4],
        [4, 1]])

In [ ]:
# DON'T WRITE HERE

tensor([[3, 4],
        [2, 4],
        [4, 1]])


### 7. Вернуть правый столбец тензора х

In [18]:
x[:,1:]

tensor([[4],
        [4],
        [1]])

In [ ]:
# DON'T WRITE HERE

tensor([[4],
        [4],
        [1]])


### 8. Не изменяя x, вернуть тензор квадратов значений x
Есть несколько способов сделать это.

In [19]:
x ** 2

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])

In [20]:
x.pow(2)

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])

In [21]:
torch.mul(x, x)

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])

In [22]:
torch.square(x)

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])

In [ ]:
# DON'T WRITE HERE

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])


### Создайте тензор "y" с тем же числом элементов, что и x, который можно умножить на матрицу с x
Используйте PyTorch напрямую (не NumPy), чтобы создать тензор случайных целых чисел от 0 (включительно) до 5 (исключительно).
Подумайте о том, какую форму должна иметь матрица для умножения.

In [23]:
y = torch.randint(0, 5, (2, 3))
y

tensor([[2, 2, 1],
        [4, 1, 0]])

In [ ]:
# DON'T WRITE HERE

tensor([[2, 2, 1],
        [4, 1, 0]])


### 10. Найти матричное произведение х и у

In [24]:
torch.matmul(x, y)

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])

In [25]:
torch.mm(x, y)

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])

In [26]:
x@y

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])

In [ ]:
# DON'T WRITE HERE

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])
